=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'uri'

module SwaggerClient
  class CoachesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get coach records and school history
    # Coaching history
    # @param [Hash] opts the optional parameters
    # @option opts [String] :first_name First name filter
    # @option opts [String] :last_name Last name filter
    # @option opts [String] :team Team name filter
    # @option opts [Integer] :year Year filter
    # @option opts [Integer] :min_year Minimum year filter (inclusive)
    # @option opts [Integer] :max_year Maximum year filter (inclusive)
    # @return [InlineResponse200]
    def get_coaches(opts = {})
      data, _status_code, _headers = get_coaches_with_http_info(opts)
      data
    end

    # Get coach records and school history
    # Coaching history
    # @param [Hash] opts the optional parameters
    # @option opts [String] :first_name First name filter
    # @option opts [String] :last_name Last name filter
    # @option opts [String] :team Team name filter
    # @option opts [Integer] :year Year filter
    # @option opts [Integer] :min_year Minimum year filter (inclusive)
    # @option opts [Integer] :max_year Maximum year filter (inclusive)
    # @return [Array<(InlineResponse200, Fixnum, Hash)>] InlineResponse200 data, response status code and response headers
    def get_coaches_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CoachesApi.get_coaches ...'
      end
      # resource path
      local_var_path = '/coaches'

      # query parameters
      query_params = {}
      query_params[:'firstName'] = opts[:'first_name'] if !opts[:'first_name'].nil?
      query_params[:'lastName'] = opts[:'last_name'] if !opts[:'last_name'].nil?
      query_params[:'team'] = opts[:'team'] if !opts[:'team'].nil?
      query_params[:'year'] = opts[:'year'] if !opts[:'year'].nil?
      query_params[:'minYear'] = opts[:'min_year'] if !opts[:'min_year'].nil?
      query_params[:'maxYear'] = opts[:'max_year'] if !opts[:'max_year'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse200')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CoachesApi#get_coaches\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
