=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'uri'

module SwaggerClient
  class ConferencesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get conference list
    # Conferences
    # @param [Hash] opts the optional parameters
    # @return [Array<Conference>]
    def get_conferences(opts = {})
      data, _status_code, _headers = get_conferences_with_http_info(opts)
      data
    end

    # Get conference list
    # Conferences
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Conference>, Fixnum, Hash)>] Array<Conference> data, response status code and response headers
    def get_conferences_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ConferencesApi.get_conferences ...'
      end
      # resource path
      local_var_path = '/conferences'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Conference>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ConferencesApi#get_conferences\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
