=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'uri'

module SwaggerClient
  class DrivesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get drive information
    # Drive results
    # @param year Year filter
    # @param [Hash] opts the optional parameters
    # @option opts [String] :season_type Season type filter (default to regular)
    # @option opts [Integer] :week Week filter
    # @option opts [String] :team Team filter
    # @option opts [String] :offense Offensive team filter
    # @option opts [String] :defense Defensive team filter
    # @option opts [String] :conference Conference filter
    # @option opts [String] :offense_conference Offensive conference filter
    # @option opts [String] :defense_conference Defensive conference filter
    # @return [Array<Drive>]
    def get_drvies(year, opts = {})
      data, _status_code, _headers = get_drvies_with_http_info(year, opts)
      data
    end

    # Get drive information
    # Drive results
    # @param year Year filter
    # @param [Hash] opts the optional parameters
    # @option opts [String] :season_type Season type filter
    # @option opts [Integer] :week Week filter
    # @option opts [String] :team Team filter
    # @option opts [String] :offense Offensive team filter
    # @option opts [String] :defense Defensive team filter
    # @option opts [String] :conference Conference filter
    # @option opts [String] :offense_conference Offensive conference filter
    # @option opts [String] :defense_conference Defensive conference filter
    # @return [Array<(Array<Drive>, Fixnum, Hash)>] Array<Drive> data, response status code and response headers
    def get_drvies_with_http_info(year, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: DrivesApi.get_drvies ...'
      end
      # verify the required parameter 'year' is set
      if @api_client.config.client_side_validation && year.nil?
        fail ArgumentError, "Missing the required parameter 'year' when calling DrivesApi.get_drvies"
      end
      # resource path
      local_var_path = '/drives'

      # query parameters
      query_params = {}
      query_params[:'year'] = year
      query_params[:'seasonType'] = opts[:'season_type'] if !opts[:'season_type'].nil?
      query_params[:'week'] = opts[:'week'] if !opts[:'week'].nil?
      query_params[:'team'] = opts[:'team'] if !opts[:'team'].nil?
      query_params[:'offense'] = opts[:'offense'] if !opts[:'offense'].nil?
      query_params[:'defense'] = opts[:'defense'] if !opts[:'defense'].nil?
      query_params[:'conference'] = opts[:'conference'] if !opts[:'conference'].nil?
      query_params[:'offenseConference'] = opts[:'offense_conference'] if !opts[:'offense_conference'].nil?
      query_params[:'defenseConference'] = opts[:'defense_conference'] if !opts[:'defense_conference'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Drive>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DrivesApi#get_drvies\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
