=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BettingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BettingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BettingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BettingApi' do
    it 'should create an instance of BettingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BettingApi)
    end
  end

  # unit tests for get_lines
  # Get betting line information
  # Closing betting lines
  # @param year Year/season filter for games
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :week Week filter
  # @option opts [String] :season_type Season type filter (regular or postseason)
  # @option opts [String] :team Team
  # @option opts [String] :home Home team filter
  # @option opts [String] :away Away team filter
  # @option opts [String] :conference Conference abbreviation filter
  # @return [Array<GameLines>]
  describe 'get_lines test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
