=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CoachesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CoachesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CoachesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CoachesApi' do
    it 'should create an instance of CoachesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CoachesApi)
    end
  end

  # unit tests for get_coaches
  # Get coach records and school history
  # Coaching history
  # @param [Hash] opts the optional parameters
  # @option opts [String] :first_name First name filter
  # @option opts [String] :last_name Last name filter
  # @option opts [String] :team Team name filter
  # @option opts [Integer] :year Year filter
  # @option opts [Integer] :min_year Minimum year filter (inclusive)
  # @option opts [Integer] :max_year Maximum year filter (inclusive)
  # @return [InlineResponse200]
  describe 'get_coaches test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
