=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DrivesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DrivesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DrivesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DrivesApi' do
    it 'should create an instance of DrivesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DrivesApi)
    end
  end

  # unit tests for get_drvies
  # Get drive information
  # Drive results
  # @param year Year filter
  # @param [Hash] opts the optional parameters
  # @option opts [String] :season_type Season type filter
  # @option opts [Integer] :week Week filter
  # @option opts [String] :team Team filter
  # @option opts [String] :offense Offensive team filter
  # @option opts [String] :defense Defensive team filter
  # @option opts [String] :conference Conference filter
  # @option opts [String] :offense_conference Offensive conference filter
  # @option opts [String] :defense_conference Defensive conference filter
  # @return [Array<Drive>]
  describe 'get_drvies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
