=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PlayersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PlayersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PlayersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlayersApi' do
    it 'should create an instance of PlayersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PlayersApi)
    end
  end

  # unit tests for get_player_usage
  # Get player usage metrics for the season
  # Player usage metrics by season
  # @param year Year filter
  # @param [Hash] opts the optional parameters
  # @option opts [String] :team Team filter
  # @option opts [String] :conference Conference abbreviation filter
  # @option opts [String] :position Position abbreviation filter
  # @option opts [Integer] :player_id Player id filter
  # @option opts [BOOLEAN] :exclude_garbage_time Filter to remove garbage time plays from calculations
  # @return [Array<PlayerUsage>]
  describe 'get_player_usage test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for player_search
  # Search for players
  # Search for players
  # @param search_term Term to search on
  # @param [Hash] opts the optional parameters
  # @option opts [String] :position Position abbreviation filter
  # @option opts [String] :team Team filter
  # @return [Array<PlayerSearchResult>]
  describe 'player_search test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
