=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RankingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RankingsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RankingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RankingsApi' do
    it 'should create an instance of RankingsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RankingsApi)
    end
  end

  # unit tests for get_rankings
  # Get historical rankings and polls
  # Poll rankings
  # @param year Year/season filter for games
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :week Week filter
  # @option opts [String] :season_type Season type filter (regular or postseason)
  # @return [Array<RankingWeek>]
  describe 'get_rankings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
