=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RatingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RatingsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RatingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RatingsApi' do
    it 'should create an instance of RatingsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RatingsApi)
    end
  end

  # unit tests for get_conference_sp_ratings
  # Get average S&amp;P+ historical rating data by conference
  # Conference average S&amp;P+ ratings by year
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Season filter
  # @option opts [String] :conference Conference abbreviation filter
  # @return [Array<ConferenceSPRating>]
  describe 'get_conference_sp_ratings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sp_ratings
  # Get S&amp;P+ historical rating data (requires either a year or team specified)
  # S&amp;P+ rating data
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Season filter (required if team not specified)
  # @option opts [String] :team Team filter (required if year not specified)
  # @return [Array<TeamSPRating>]
  describe 'get_sp_ratings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
