=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RecruitingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RecruitingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RecruitingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RecruitingApi' do
    it 'should create an instance of RecruitingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RecruitingApi)
    end
  end

  # unit tests for get_recruiting_groups
  # Get position group aggregated ratings
  # Gets a list of aggregated statistics by team and position grouping
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start_year Starting year
  # @option opts [Integer] :end_year Ending year
  # @option opts [String] :team Team filter
  # @option opts [String] :conference conference filter
  # @return [Array<PositionGroupRecruitingRating>]
  describe 'get_recruiting_groups test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_recruiting_players
  # Get player recruiting rankings and data. Requires either a year or team to be specified.
  # Player recruiting rankings
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Recruiting class year (required if team no specified)
  # @option opts [String] :classification Type of recruit (HighSchool, JUCO, PrepSchool)
  # @option opts [String] :position Position abbreviation filter
  # @option opts [String] :state State or province abbreviation filter
  # @option opts [String] :team Committed team filter (required if year not specified)
  # @return [Array<Recruit>]
  describe 'get_recruiting_players test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_recruiting_teams
  # Get team recruiting rankings
  # Team recruiting rankings
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Recruiting class year
  # @option opts [String] :team Team filter
  # @return [Array<TeamRecruitingRank>]
  describe 'get_recruiting_teams test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
