=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::StatsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::StatsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatsApi' do
    it 'should create an instance of StatsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::StatsApi)
    end
  end

  # unit tests for get_advanced_team_game_stats
  # Get advanced game team stats
  # Advanced team game stats
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Year filter (required if no team specified)
  # @option opts [Integer] :week Week filter
  # @option opts [String] :team Team filter (required if no year specified)
  # @option opts [String] :opponent Opponent filter
  # @option opts [BOOLEAN] :exclude_garbage_time Filter to remove garbage time plays from calculations
  # @return [Array<AdvancedGameStat>]
  describe 'get_advanced_team_game_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_advanced_team_season_stats
  # Get advanced season team stats
  # Advanced team season stats
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Year filter (required if no team specified)
  # @option opts [String] :team Team filter (required if no year specified)
  # @option opts [BOOLEAN] :exclude_garbage_time Filter to remove garbage time plays from calculations
  # @option opts [Integer] :start_week Starting week filter
  # @option opts [Integer] :end_week Starting week filter
  # @return [Array<AdvancedSeasonStat>]
  describe 'get_advanced_team_season_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_stat_categories
  # Get stat category list
  # Stat category list
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'get_stat_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_team_season_stats
  # Get season team stats
  # Team season stats
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :year Year filter (required if no team specified)
  # @option opts [String] :team Team filter (required if no year specified)
  # @option opts [String] :conference Conference abbreviation filter
  # @option opts [Integer] :start_week Starting week filter
  # @option opts [Integer] :end_week Starting week filter
  # @return [Array<TeamSeasonStat>]
  describe 'get_team_season_stats test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
