=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'date'

module SwaggerClient
  class BoxScoreTeams
    attr_accessor :ppa

    attr_accessor :success_rates

    attr_accessor :explosiveness

    attr_accessor :rushing

    attr_accessor :havoc

    attr_accessor :scoring_opportunities

    attr_accessor :field_position

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ppa' => :'ppa',
        :'success_rates' => :'successRates',
        :'explosiveness' => :'explosiveness',
        :'rushing' => :'rushing',
        :'havoc' => :'havoc',
        :'scoring_opportunities' => :'scoringOpportunities',
        :'field_position' => :'fieldPosition'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'ppa' => :'Array<BoxScoreTeamsPpa>',
        :'success_rates' => :'Array<BoxScoreTeamsSuccessRates>',
        :'explosiveness' => :'Array<BoxScoreTeamsExplosiveness>',
        :'rushing' => :'Array<BoxScoreTeamsRushing>',
        :'havoc' => :'Array<BoxScoreTeamsHavoc>',
        :'scoring_opportunities' => :'Array<BoxScoreTeamsScoringOpportunities>',
        :'field_position' => :'Array<BoxScoreTeamsFieldPosition>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'ppa')
        if (value = attributes[:'ppa']).is_a?(Array)
          self.ppa = value
        end
      end

      if attributes.has_key?(:'successRates')
        if (value = attributes[:'successRates']).is_a?(Array)
          self.success_rates = value
        end
      end

      if attributes.has_key?(:'explosiveness')
        if (value = attributes[:'explosiveness']).is_a?(Array)
          self.explosiveness = value
        end
      end

      if attributes.has_key?(:'rushing')
        if (value = attributes[:'rushing']).is_a?(Array)
          self.rushing = value
        end
      end

      if attributes.has_key?(:'havoc')
        if (value = attributes[:'havoc']).is_a?(Array)
          self.havoc = value
        end
      end

      if attributes.has_key?(:'scoringOpportunities')
        if (value = attributes[:'scoringOpportunities']).is_a?(Array)
          self.scoring_opportunities = value
        end
      end

      if attributes.has_key?(:'fieldPosition')
        if (value = attributes[:'fieldPosition']).is_a?(Array)
          self.field_position = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ppa == o.ppa &&
          success_rates == o.success_rates &&
          explosiveness == o.explosiveness &&
          rushing == o.rushing &&
          havoc == o.havoc &&
          scoring_opportunities == o.scoring_opportunities &&
          field_position == o.field_position
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [ppa, success_rates, explosiveness, rushing, havoc, scoring_opportunities, field_position].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
