=begin
#College Football Data API

#This is an API for accessing all sorts of college football data.  It currently has a wide array of data ranging from play by play to player statistics to game scores and more.

OpenAPI spec version: 1.20.0
Contact: admin@collegefootballdata.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/advanced_game_stat'
require 'swagger_client/models/advanced_game_stat_offense'
require 'swagger_client/models/advanced_game_stat_offense_standard_downs'
require 'swagger_client/models/advanced_season_stat'
require 'swagger_client/models/advanced_season_stat_defense'
require 'swagger_client/models/advanced_season_stat_offense'
require 'swagger_client/models/advanced_season_stat_offense_field_position'
require 'swagger_client/models/advanced_season_stat_offense_standard_downs'
require 'swagger_client/models/box_score'
require 'swagger_client/models/box_score_players'
require 'swagger_client/models/box_score_players_average'
require 'swagger_client/models/box_score_players_ppa'
require 'swagger_client/models/box_score_players_usage'
require 'swagger_client/models/box_score_teams'
require 'swagger_client/models/box_score_teams_explosiveness'
require 'swagger_client/models/box_score_teams_field_position'
require 'swagger_client/models/box_score_teams_havoc'
require 'swagger_client/models/box_score_teams_overall'
require 'swagger_client/models/box_score_teams_ppa'
require 'swagger_client/models/box_score_teams_rushing'
require 'swagger_client/models/box_score_teams_scoring_opportunities'
require 'swagger_client/models/box_score_teams_success_rates'
require 'swagger_client/models/conference'
require 'swagger_client/models/conference_sp_rating'
require 'swagger_client/models/drive'
require 'swagger_client/models/drive_start_time'
require 'swagger_client/models/game'
require 'swagger_client/models/game_lines'
require 'swagger_client/models/game_lines_lines'
require 'swagger_client/models/game_ppa'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/play'
require 'swagger_client/models/play_stat'
require 'swagger_client/models/play_stat_type'
require 'swagger_client/models/play_type'
require 'swagger_client/models/play_wp'
require 'swagger_client/models/player'
require 'swagger_client/models/player_game'
require 'swagger_client/models/player_game_athletes'
require 'swagger_client/models/player_game_categories'
require 'swagger_client/models/player_game_ppa'
require 'swagger_client/models/player_game_ppa_average_ppa'
require 'swagger_client/models/player_game_school'
require 'swagger_client/models/player_game_teams'
require 'swagger_client/models/player_game_types'
require 'swagger_client/models/player_search_result'
require 'swagger_client/models/player_season_ppa'
require 'swagger_client/models/player_season_ppa_average_ppa'
require 'swagger_client/models/player_usage'
require 'swagger_client/models/player_usage_usage'
require 'swagger_client/models/position_group_recruiting_rating'
require 'swagger_client/models/predicted_points'
require 'swagger_client/models/pregame_wp'
require 'swagger_client/models/ranking_week'
require 'swagger_client/models/ranking_week_polls'
require 'swagger_client/models/ranking_week_ranks'
require 'swagger_client/models/recruit'
require 'swagger_client/models/team'
require 'swagger_client/models/team_game'
require 'swagger_client/models/team_game_stats'
require 'swagger_client/models/team_game_teams'
require 'swagger_client/models/team_matchup'
require 'swagger_client/models/team_matchup_games'
require 'swagger_client/models/team_ppa'
require 'swagger_client/models/team_ppa_offense'
require 'swagger_client/models/team_recruiting_rank'
require 'swagger_client/models/team_sp_rating'
require 'swagger_client/models/team_sp_rating_defense'
require 'swagger_client/models/team_sp_rating_defense_havoc'
require 'swagger_client/models/team_sp_rating_offense'
require 'swagger_client/models/team_sp_rating_special_teams'
require 'swagger_client/models/team_season'
require 'swagger_client/models/team_season_stat'
require 'swagger_client/models/team_talent'
require 'swagger_client/models/venue'
require 'swagger_client/models/venue_location'

# APIs
require 'swagger_client/api/betting_api'
require 'swagger_client/api/coaches_api'
require 'swagger_client/api/conferences_api'
require 'swagger_client/api/drives_api'
require 'swagger_client/api/games_api'
require 'swagger_client/api/metrics_api'
require 'swagger_client/api/players_api'
require 'swagger_client/api/plays_api'
require 'swagger_client/api/rankings_api'
require 'swagger_client/api/ratings_api'
require 'swagger_client/api/recruiting_api'
require 'swagger_client/api/stats_api'
require 'swagger_client/api/teams_api'
require 'swagger_client/api/venues_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
